version: '3.8'
services:
  myblog:
    build: .
      image: myblog
      depends_on:
        - redis
        - mysql
      ports:
#容器内部 ： 外部
        - "8080:8080"
  redis:
    image: "redis:alpine"
  mysql:
    restart: always
    image: "mysql:5.7"
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=root"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306

